[package]
name = "swieng-colorgen"
version = "0.1.2"
edition = "2021"

[dependencies]
image = {version = "0.25.5", default-features = true}
palette = "0.7.6"

[profile.release]
strip = true
opt-level = 2
lto = true
codegen-units = 1
